// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCftjhw2LwlNnx_KGajeQXDPsUDnD_9iuM',
    appId: '1:902826544206:web:943e679a6841660a24c71f',
    messagingSenderId: '902826544206',
    projectId: 'bondu-dfe48',
    authDomain: 'bondu-dfe48.firebaseapp.com',
    storageBucket: 'bondu-dfe48.appspot.com',
    measurementId: 'G-FWDV431T03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ4rFW_LSjZqGswyaHXra72kLeBpdVx2A',
    appId: '1:902826544206:android:d971d9059b59ed0124c71f',
    messagingSenderId: '902826544206',
    projectId: 'bondu-dfe48',
    storageBucket: 'bondu-dfe48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIGO_RVDKVFS58tT2VehmpeWWuadJbwjw',
    appId: '1:902826544206:ios:033a209856d454a924c71f',
    messagingSenderId: '902826544206',
    projectId: 'bondu-dfe48',
    storageBucket: 'bondu-dfe48.appspot.com',
    iosBundleId: 'com.example.bondu',
  );
}
